### ISSUE TITLE
umm plz rell me why do i get this error and the solution plz plz plz

### ISSUE THREAD

**Issue by LakshithJaiswal** [python-engineer/pytorch-chatbot#10]
C:\Users\lukky\PycharmProjects\jarvis2.0>C:/Users/lukky/AppData/Local/Programs/Python/Python39/python.exe c:/Users/lukky/PycharmProjects/jarvis2.0/chatbot.py
Traceback (most recent call last):
  File "c:\Users\lukky\PycharmProjects\jarvis2.0\chatbot.py", line 4, in <module>
    import torch
  File "C:\Users\lukky\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\__init__.py", line 118, in <module>
    raise err
OSError: [WinError 193] %1 is not a valid Win32 application. Error loading "C:\Users\lukky\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\lib\caffe2_detectron_ops.dll" or one of its dependencies.

**Comment by patrickloeber** [comment]
The most common case for this error, is an architecture mismatch:

64bit process attempting to load a 32bit .dll
32bit process attempting to load a 64bit .dll

probably some of your installations are not correct

**Comment by LakshithJaiswal** [comment]
so any solutions for it btw the first youtuber to respond my question ever tqs ill try

**Comment by LakshithJaiswal** [comment]
and i have a 64 bit windows

**Comment by LakshithJaiswal** [comment]
bro i got the solution i was using the wrong py thorch i juss deleted it and reinstalled it. it worked tqs bro

**Comment by patrickloeber** [comment]
Awesome! Have fun with the project :)
