### ISSUE TITLE
Runtime error in train.py

### ISSUE THREAD

**Issue by kenil84** [python-engineer/pytorch-chatbot#3]
raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))

RuntimeError: DataLoader worker (pid(s) 21184, 8440) exited unexpectedly

**Comment by borhanreo** [comment]
I think you run on your code in CPU machine. if yes, then you have change two places in train.py
1: Change In line 84 `num_workers=2` to `num_workers=0`
2: Add this after 98 line  `labels = labels.to(dtype=torch.long)` **(after labels = labels.to(device)**
