### ISSUE TITLE
not implemented error

### ISSUE THREAD

**Issue by SureshP44** [python-engineer/pytorch-chatbot#4]
when  i try to print no of epoch and loss rate, I faced this issue that tells "Not Implemented Error"

**Comment by ankitdata** [comment]
Hi,
can you share your code so that i can reproduce this issue. and also machine info.

**Comment by SureshP44** [comment]
Thanks for your kindness...

Actually, I resolved it and now i forgot what actually the error is...

**Comment by python-engineer** [comment]
Sorry for the late response, I completely missed this issue. But great that you could fix it
